/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2programacion2;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Leonel Thomas
 */
public class Citas extends javax.swing.JFrame {

    
    
    public Citas() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ImageIcon citas = new ImageIcon(getClass().getResource("/Imagenes/agenda.png"));
        Icon fondo = new ImageIcon(citas.getImage().getScaledInstance(Citas.getWidth(), Citas.getHeight(), Image.SCALE_DEFAULT));
        Citas.setIcon(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reportes1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NuevaCita = new javax.swing.JButton();
        EditarFecha = new javax.swing.JButton();
        MostrarCita = new javax.swing.JButton();
        CancelarCita = new javax.swing.JButton();
        AtenderCita = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Citas = new javax.swing.JLabel();

        Reportes1.setBackground(new java.awt.Color(0, 0, 204));
        Reportes1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Reportes1.setForeground(new java.awt.Color(255, 255, 255));
        Reportes1.setText("REPORTES");
        Reportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reportes1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Citas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        NuevaCita.setBackground(new java.awt.Color(0, 0, 204));
        NuevaCita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NuevaCita.setForeground(new java.awt.Color(255, 255, 255));
        NuevaCita.setText("Nueva Cita");
        NuevaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCitaActionPerformed(evt);
            }
        });

        EditarFecha.setBackground(new java.awt.Color(0, 0, 204));
        EditarFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EditarFecha.setForeground(new java.awt.Color(255, 255, 255));
        EditarFecha.setText("Editar fecha de cita");
        EditarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarFechaActionPerformed(evt);
            }
        });

        MostrarCita.setBackground(new java.awt.Color(0, 0, 204));
        MostrarCita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MostrarCita.setForeground(new java.awt.Color(255, 255, 255));
        MostrarCita.setText("Mostrar Cita");
        MostrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarCitaActionPerformed(evt);
            }
        });

        CancelarCita.setBackground(new java.awt.Color(0, 0, 204));
        CancelarCita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CancelarCita.setForeground(new java.awt.Color(255, 255, 255));
        CancelarCita.setText("Cancelar Cita");
        CancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCitaActionPerformed(evt);
            }
        });

        AtenderCita.setBackground(new java.awt.Color(0, 0, 204));
        AtenderCita.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AtenderCita.setForeground(new java.awt.Color(255, 255, 255));
        AtenderCita.setText("Atender Cita");
        AtenderCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtenderCitaActionPerformed(evt);
            }
        });

        MenuPrincipal.setBackground(new java.awt.Color(0, 255, 0));
        MenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        MenuPrincipal.setText("Menu Principal");
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AtenderCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelarCita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MostrarCita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NuevaCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(MenuPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(NuevaCita)
                .addGap(18, 18, 18)
                .addComponent(EditarFecha)
                .addGap(18, 18, 18)
                .addComponent(MostrarCita)
                .addGap(18, 18, 18)
                .addComponent(CancelarCita)
                .addGap(18, 18, 18)
                .addComponent(AtenderCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(MenuPrincipal)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(290, 60, 400, 420);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Citas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(Citas, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 60, 290, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCitaActionPerformed
       NuevaCita NC = new NuevaCita();
        NC.setVisible(true);
        NC.pack();
        NC.setLocationRelativeTo(null);
        NC.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_NuevaCitaActionPerformed

    private void Reportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reportes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reportes1ActionPerformed

    private void EditarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarFechaActionPerformed
        // TODO add your handling code here:
        EditarFechaCita EF = new EditarFechaCita();
        EF.setVisible(true);
        EF.pack();
        EF.setLocationRelativeTo(null);
        EF.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_EditarFechaActionPerformed

    private void MostrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarCitaActionPerformed

    private void CancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCitaActionPerformed
       CancelarCita CC = new CancelarCita();
        CC.setVisible(true);
        CC.pack();
        CC.setLocationRelativeTo(null);
        CC.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_CancelarCitaActionPerformed

    private void AtenderCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtenderCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtenderCitaActionPerformed

    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        m.pack();
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtenderCita;
    private javax.swing.JButton CancelarCita;
    private javax.swing.JLabel Citas;
    private javax.swing.JButton EditarFecha;
    private javax.swing.JButton MenuPrincipal;
    private javax.swing.JButton MostrarCita;
    private javax.swing.JButton NuevaCita;
    private javax.swing.JButton Reportes1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
